import type { Product, Collection } from "@/types";

export const COLLECTIONS: Collection[] = [
  {
    slug: "core",
    name: "Core",
    number: "01",
    tagline: "Essentials perfected. Every silhouette, every day.",
    description:
      "The foundation of the GAZE wardrobe. Essentials engineered for long wear, tropical climates, and daily confidence. Cut from our Supima Modal blend with precision tolerances uncommon in the category.",
  },
  {
    slug: "after-dark",
    name: "After Dark",
    number: "02",
    tagline: "For evenings that demand a finer edge.",
    description:
      "Sheer, structured, intimate. A line for evenings that begin after the room quiets. Japanese micro-voile, Coolmax blends, and silhouettes that require certainty of taste.",
  },
  {
    slug: "resort",
    name: "Resort",
    number: "03",
    tagline: "Heat-engineered. Made for the tropics.",
    description:
      "Swim and leisure pieces engineered for heat, salt water, and slow tropical afternoons. ECONYL® recycled nylon throughout. Chlorine-resistant, fast-drying, and uncompromising on cut.",
  },
  {
    slug: "vault",
    name: "Vault",
    number: "04",
    tagline: "Limited editions. Private access pieces.",
    description:
      "Numbered editions. Rare compositions. Released in limited runs to private-access members. Each Vault piece is individually numbered and accompanied by a certificate of provenance.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p01",
    slug: "nocturne-brief",
    name: "Nocturne Brief",
    collection: "core",
    collectionName: "Core",
    short: "A low-rise brief with a cleaner line and cooler hand.",
    long: "Cut from our Supima Modal blend at a precise low-rise, the Nocturne Brief is the flagship of the Core line. The seams are flat-felled. The pouch is anatomically positioned. The waistband is 35mm of smooth jacquard without print or logo. A piece designed to disappear — until it does not. Washes at 30°C, retains its shape across three years of daily use. Available in three considered colourways.",
    price: 98,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian", hex: "#1c1a18" },
      { name: "Charcoal", hex: "#3d3530" },
      { name: "Bone", hex: "#c8bfb0" },
    ],
    badge: null,
    specs: {
      Silhouette: "Brief",
      Composition: "70% Supima Cotton, 25% Modal, 5% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Contour pouch",
      Waistband: "35mm jacquard, logo-free",
      Opacity: "Opaque",
      Cooling: "Moderate",
      Stretch: "Four-way",
      Country: "Thailand",
    },
    isNew: false,
    isBestSeller: false,
  },
  {
    id: "p02",
    slug: "nocturne-boxer-brief",
    name: "Nocturne Boxer Brief",
    collection: "core",
    collectionName: "Core",
    short: "The Nocturne silhouette extended. Same fabric, longer line.",
    long: "For those who prefer coverage with the same material precision. The Boxer Brief version of the Nocturne sits at the same low-rise but extends to mid-thigh. Clean inseam. No ride-up. The flat-felled seams of the original, scaled to a fuller silhouette. A daily essential elevated to something worth noticing. Made in limited runs of each colourway per season.",
    price: 112,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian", hex: "#1c1a18" },
      { name: "Tobacco", hex: "#6b5c4d" },
      { name: "Bone", hex: "#c8bfb0" },
    ],
    badge: "Best Seller",
    specs: {
      Silhouette: "Boxer Brief",
      Composition: "70% Supima Cotton, 25% Modal, 5% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Contour pouch",
      Waistband: "35mm jacquard, logo-free",
      Opacity: "Opaque",
      Cooling: "Moderate",
      Stretch: "Four-way",
      Country: "Thailand",
    },
    isBestSeller: true,
  },
  {
    id: "p03",
    slug: "obsidian-trunk",
    name: "Obsidian Trunk",
    collection: "core",
    collectionName: "Core",
    short: "A mid-rise trunk with structured support and quiet authority.",
    long: "The Obsidian Trunk sits at the natural waist and cuts to the upper thigh. A moderate-coverage silhouette with a structured pouch and clean hem. Made from our darker Supima Modal blend for maximum depth and a weight that moves with purpose. The waistband is wider than the Brief — 40mm of flat jacquard — providing additional support across longer wear.",
    price: 108,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian", hex: "#1c1a18" },
      { name: "Espresso", hex: "#3d3530" },
    ],
    badge: null,
    specs: {
      Silhouette: "Trunk",
      Composition: "68% Supima Cotton, 27% Modal, 5% Elastane",
      Fit: "Mid-rise",
      Rise: "Mid",
      Support: "Structured pouch",
      Waistband: "40mm flat, logo-free",
      Opacity: "Opaque",
      Cooling: "Low–moderate",
      Stretch: "Four-way",
      Country: "Thailand",
    },
  },
  {
    id: "p04",
    slug: "bone-rib-brief",
    name: "Bone Rib Brief",
    collection: "core",
    collectionName: "Core",
    short: "Heavy-gauge Portuguese rib. Substantial. Precise.",
    long: "Cut from a heavier ribbed cotton sourced from a specialist Portuguese hosiery mill. The Bone Rib Brief has a weight and texture that sets it apart from the Core Supima pieces. Structured. Self-supporting. With a waistband that remembers its shape across years of wear. Two colourways: the natural Bone and a deeper Walnut. Both are deliberately uncommon.",
    price: 118,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Bone", hex: "#c8bfb0" },
      { name: "Walnut", hex: "#6b5c4d" },
    ],
    badge: "New",
    specs: {
      Silhouette: "Brief",
      Composition: "92% Cotton, 8% Elastane",
      Fit: "Mid-rise",
      Rise: "Mid",
      Support: "Built-in rib pouch",
      Waistband: "38mm ribbed band",
      Opacity: "Opaque",
      Cooling: "Low",
      Stretch: "Two-way",
      Country: "Portugal",
    },
    isNew: true,
  },
  {
    id: "p05",
    slug: "veil-mesh-brief",
    name: "Veil Mesh Brief",
    collection: "after-dark",
    collectionName: "After Dark",
    short: "Micro-voile mesh. Near-invisible. Precisely engineered.",
    long: "The Veil Mesh Brief uses our Japanese micro-voile — an ultra-fine nylon sourced from a specialist mill in Niigata — cut to a minimal brief silhouette. The fabric catches light without announcing itself. A piece for evenings that begin with intention. The 25mm matte waistband carries no logo. Available in Shadow, Smoke, and Ash — three degrees of deliberate opacity.",
    price: 138,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Shadow", hex: "#1c1a18" },
      { name: "Smoke", hex: "#4a4540" },
      { name: "Ash", hex: "#8a857e" },
    ],
    badge: "After Dark",
    specs: {
      Silhouette: "Brief",
      Composition: "88% Nylon, 12% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Minimal",
      Waistband: "25mm elastic, matte finish",
      Opacity: "Sheer",
      Cooling: "High",
      Stretch: "Four-way",
      Country: "Thailand",
    },
  },
  {
    id: "p06",
    slug: "veil-mesh-jock",
    name: "Veil Mesh Jock",
    collection: "after-dark",
    collectionName: "After Dark",
    short: "The Veil fabric, reduced to its most deliberate form.",
    long: "The Jock silhouette from the After Dark line. Constructed from the same Japanese micro-voile as the Veil Brief but cut to minimal coverage. A piece that demands certainty of taste. The rear straps are 12mm of the same matte elastic as the waistband — clean, functional, uncontrived. Available in a limited run per season. Once sold out, not restocked until the following edition.",
    price: 148,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Shadow", hex: "#1c1a18" },
      { name: "Ash", hex: "#8a857e" },
    ],
    badge: "Limited",
    specs: {
      Silhouette: "Jock",
      Composition: "88% Nylon, 12% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Jock strap construction",
      Waistband: "25mm matte elastic",
      Opacity: "Sheer",
      Cooling: "High",
      Stretch: "Four-way",
      Country: "Thailand",
    },
  },
  {
    id: "p07",
    slug: "shadow-sheer-brief",
    name: "Shadow Sheer Brief",
    collection: "after-dark",
    collectionName: "After Dark",
    short: "A controlled translucence for men who choose what is seen.",
    long: "The Shadow Sheer is cut from a double-faced nylon mesh with a front liner panel. The result is a precise balance between visibility and propriety. Worn under tailoring or on its own, it reads as intentional. Never accidental. The composition is 82% nylon — light, responsive, and precisely cooling in humid climates.",
    price: 128,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Midnight", hex: "#0e0d0c" },
      { name: "Graphite", hex: "#2a2520" },
    ],
    badge: null,
    specs: {
      Silhouette: "Brief",
      Composition: "82% Nylon, 18% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Lined front panel",
      Waistband: "28mm clear elastic, logo-free",
      Opacity: "Semi-sheer",
      Cooling: "High",
      Stretch: "Four-way",
      Country: "Thailand",
    },
  },
  {
    id: "p08",
    slug: "eclipse-low-rise-trunk",
    name: "Eclipse Low-Rise Trunk",
    collection: "after-dark",
    collectionName: "After Dark",
    short: "Engineered for humid evenings and long wear.",
    long: "The Eclipse Trunk uses our Coolmax® blend — a four-channel moisture transport fibre — cut to a low-rise trunk silhouette. Performs in Bangkok humidity. Recovers across repeated wear. A trunk for evenings that extend into morning. The 32mm flat-band waistband sits low without shifting. Available in Obsidian and Deep Tobacco.",
    price: 142,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian", hex: "#1c1a18" },
      { name: "Deep Tobacco", hex: "#4a3828" },
    ],
    badge: "New",
    specs: {
      Silhouette: "Trunk",
      Composition: "60% Polyester Coolmax®, 30% Nylon, 10% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Contour pouch",
      Waistband: "32mm flat band",
      Opacity: "Opaque",
      Cooling: "Very high",
      Stretch: "Four-way",
      Country: "Thailand",
    },
    isNew: true,
  },
  {
    id: "p09",
    slug: "tide-swim-brief",
    name: "Tide Swim Brief",
    collection: "resort",
    collectionName: "Resort",
    short: "Salt-ready. Precise cut. Minimal profile.",
    long: "The Tide is cut from ECONYL® recycled nylon — an Italian regenerated fibre with exceptional salt and chlorine resistance. A minimal swim brief with a clean waistband and a silhouette that performs at the pool or the ocean without compromising on cut. Dries in under 20 minutes. Retains colour and opacity across multiple seasons of use.",
    price: 158,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian", hex: "#1c1a18" },
      { name: "Sand", hex: "#c8b898" },
      { name: "Bone", hex: "#e8e0d4" },
    ],
    badge: null,
    specs: {
      Silhouette: "Swim Brief",
      Composition: "78% ECONYL® Nylon, 22% Elastane",
      Fit: "Sport-rise",
      Rise: "Sport",
      Support: "Lined",
      Waistband: "35mm recycled elastic",
      Opacity: "Opaque wet and dry",
      Cooling: "N/A",
      Stretch: "Four-way",
      Country: "Italy / Thailand",
    },
  },
  {
    id: "p10",
    slug: "heatwave-short-trunk",
    name: "Heatwave Short Trunk",
    collection: "resort",
    collectionName: "Resort",
    short: "A short trunk for the pool and beyond. Stays where it is placed.",
    long: "The Heatwave Short Trunk is cut fractionally longer than a swim brief but shorter than a full trunk. Designed for resort environments — pool, beach, spa — where a piece must function across multiple contexts. ECONYL® nylon throughout. Dries fast. Holds shape across seasons. The 38mm recycled elastic waistband is flat and discreet. Available in three colourways.",
    price: 168,
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Navy", hex: "#1a2535" },
      { name: "Sand", hex: "#c8b898" },
      { name: "Obsidian", hex: "#1c1a18" },
    ],
    badge: "Best Seller",
    specs: {
      Silhouette: "Short Trunk",
      Composition: "78% ECONYL® Nylon, 22% Elastane",
      Fit: "Mid-rise",
      Rise: "Mid",
      Support: "Lined",
      Waistband: "38mm recycled elastic",
      Opacity: "Opaque wet and dry",
      Cooling: "N/A",
      Stretch: "Four-way",
      Country: "Italy / Thailand",
    },
    isBestSeller: true,
  },
  {
    id: "p11",
    slug: "midnight-harness-brief",
    name: "Midnight Harness Brief",
    collection: "vault",
    collectionName: "Vault",
    short: "Soft hold. Precise cut. Discreet finish.",
    long: "The Midnight Harness Brief is a numbered piece from the Vault line. Cut from a structured nylon-elastane, it incorporates a minimal integrated harness element — a single rear strap — without the noise of club-wear styling. A piece for men who understand subtlety. Limited to 150 units per season. Each piece carries a numbered interior tag and a certificate of provenance dispatched separately.",
    price: 228,
    sizes: ["S", "M", "L"],
    colors: [{ name: "Obsidian", hex: "#1c1a18" }],
    badge: "Vault",
    specs: {
      Silhouette: "Brief with harness detail",
      Composition: "80% Nylon, 20% Elastane",
      Fit: "Low-rise",
      Rise: "Low",
      Support: "Structured front",
      Waistband: "32mm matte elastic",
      Opacity: "Opaque",
      Cooling: "High",
      Stretch: "Four-way",
      Country: "Thailand",
    },
  },
  {
    id: "p12",
    slug: "private-satin-brief",
    name: "Private Satin Brief",
    collection: "vault",
    collectionName: "Vault",
    short: "A silk-weight satin for those who understand the difference.",
    long: "The Private Satin Brief uses a French charmeuse satin — a silk-weight weave with exceptional drape, cool temperature feel, and a surface that rewards stillness. Cut to a clean mid-rise brief silhouette with French seams and a logo-free waistband. Available in a numbered edition of 80 units. Champagne and Obsidian. Both carry the same provenance documentation as all Vault pieces.",
    price: 268,
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Champagne", hex: "#d4c4a0" },
      { name: "Obsidian", hex: "#1c1a18" },
    ],
    badge: "Vault",
    specs: {
      Silhouette: "Brief",
      Composition: "94% Silk-weight Polyester, 6% Elastane",
      Fit: "Mid-rise",
      Rise: "Mid",
      Support: "Minimal",
      Waistband: "28mm satin-faced elastic",
      Opacity: "Opaque",
      Cooling: "High",
      Stretch: "Two-way",
      Country: "France / Thailand",
    },
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCollection(collection: string): Product[] {
  return PRODUCTS.filter((p) => p.collection === collection);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.collection === product.collection && p.id !== product.id
  ).slice(0, limit);
}

export function getCollectionBySlug(
  slug: string
): Collection | undefined {
  return COLLECTIONS.find((c) => c.slug === slug);
}
